-- Idempotent registry bootstrap for a fresh D1 database created from schema.sql.
-- Run only after schema.sql, seeds/defaults.sql, and the migration-state audit pass.

CREATE TABLE IF NOT EXISTS d1_migrations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE,
  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT OR IGNORE INTO d1_migrations (name) VALUES
  ('0002_add_quiz_tags.sql'),
  ('0003_add_tags_to_questions.sql'),
  ('0004_add_perf_indexes.sql'),
  ('0005_add_gift_shop.sql'),
  ('0006_add_attendance_claims.sql'),
  ('0007_add_rag_tables.sql'),
  ('0008_add_system_settings.sql'),
  ('0009_extend_announcements.sql'),
  ('0010_add_analytics_json.sql'),
  ('0011_create_test_bank.sql'),
  ('0012_add_teacher_ai_daily_usage.sql'),
  ('0013_add_question_skill_metadata.sql'),
  ('0014_add_question_difficulty.sql'),
  ('0015_add_game_loop_tables.sql'),
  ('0016_add_live_exam_tables.sql'),
  ('0017_add_live_exam_waiting_room_chat.sql'),
  ('0018_add_live_exam_analytics.sql'),
  ('0019_add_phieu_nhanxet.sql'),
  ('0020_canonicalize_certificates.sql'),
  ('0021_certificate_template_layout.sql'),
  ('0022_default_certificate_name_font.sql'),
  ('0023_certificate_batch_text_overrides.sql'),
  ('0024_archive_classroom_records.sql'),
  ('0025_canonicalize_homework.sql'),
  ('0026_live_exam_hardening.sql'),
  ('0027_math_format_observability.sql'),
  ('0028_harden_teacher_accounts.sql'),
  ('0029_canonicalize_system_announcements.sql'),
  ('0030_backfill_result_scores.sql'),
  ('0031_add_reward_receipts.sql'),
  ('0032_add_result_report_delivery.sql'),
  ('0033_create_quiz_drafts.sql'),
  ('0034_add_question_authoring_fields.sql'),
  ('0035_add_question_image_alt.sql'),
  ('0036_seed_tohieuquiz_certificate_templates.sql'),
  ('0037_add_parent_portal_complete.sql'),
  ('0038_normalize_quiz_ownership.sql'),
  ('0039_create_ai_generation_actions.sql'),
  ('0040_scope_results_to_assignments.sql'),
  ('0041_certificate_layout_and_name_fonts.sql'),
  ('0042_unified_notifications.sql'),
  ('0043_create_rate_limits.sql'),
  ('0044_create_ai_tutor_usage.sql'),
  ('0045_live_exam_reconnect.sql'),
  ('0046_live_exam_controls.sql'),
  ('0047_results_intervention_center.sql'),
  ('0048_parent_digest_recovery.sql'),
  ('0049_gift_shop_governance.sql'),
  ('0050_notification_preferences.sql'),
  ('0051_pagination_indexes.sql'),
  ('0052_auth_sessions_security_events.sql'),
  ('0053_webauthn_passkeys.sql'),
  ('0054_feature_rollout_control_plane.sql'),
  ('0055_certificate_render_backgrounds_png.sql'),
  ('0056_add_generated_certificate_templates.sql'),
  ('0057_unified_quiz_editor_versioning.sql'),
  ('0058_canonical_quiz_scoring_v2.sql'),
  ('0059_quiz_scoring_rollout_flags.sql'),
  ('0060_system_question_bank.sql'),
  ('0061_assignment_revocation.sql'),
  ('0062_add_question_svg_diagrams.sql'),
  ('0063_certificate_footer_safe_zone.sql'),
  ('0064_add_question_rich_text.sql'),
  ('0065_add_result_canonical_class_scope.sql'),
  ('0066_student_reward_ledger.sql'),
  ('0067_intervention_group_archive_audit.sql'),
  ('0068_login_media.sql');
